/**
 * The seam for everything the public site renders that is NOT the catalogue.
 *
 * `catalog.ts` is rule 3's door for products. This is the same door for site
 * text and hero banners, and it exists for the same reason: swapping the source
 * from committed JSON to Postgres has to be a change to ONE module, not to
 * every page that happens to read a phone number.
 *
 * Stage 2 of `docs/superpowers/plans/2026-08-19-admin-content-management.md`
 * is what makes that swap, and it is what makes banner selection editable from
 * `/admin` — the admin writes rows, the build reads them through here.
 *
 * No page or component may import `src/data/hero-banners.json` directly once
 * this exists. `src/data/site.json` is still imported in fifteen places and is
 * still exempt from the seam gate; Task 8 closes that.
 */
import type { ImageMetadata } from 'astro';
import siteJson from '../data/site.json';
import { env, configured } from './env';

export interface SiteSettings {
  phone: string;
  email: string;
  address: string;
  /** Empty string means "no WhatsApp affordance", which renders nothing at all. */
  whatsapp: string;
  established: number;
  industries: string[];
  /**
   * handoff.md §8 item 5: the eight industries are inferred from the product
   * mix rather than stated in the brochure. The flag travels WITH the data so
   * the admin can show them as unconfirmed instead of presenting them as fact.
   * A caveat that lives only in a document is a caveat nobody reads.
   */
  industriesPendingClientConfirmation: boolean;
}

/**
 * Every piece of site chrome the pages render: contact details, the founding
 * year, the industries list.
 *
 * Async because `getHeroBanners` and `catalog.ts` are, and because Task 9 makes
 * this read Postgres — a caller that already awaits does not change then.
 */
export async function getSiteSettings(): Promise<SiteSettings> {
  return siteJson as SiteSettings;
}

export interface HeroBanner {
  id: string;
  /**
   * The banner as an ordinary local asset, resolved from
   * `src/assets/banners/` — which `tools/fetch-banners.mjs` fills from the
   * private bucket before every build.
   *
   * IT IS A LOCAL FILE ON PURPOSE, AND THAT IS A CACHE DECISION. `<Picture>`
   * used to fetch a signed URL directly, and Astro names an emitted asset from
   * a hash of its source — so a signed URL, whose token is minted fresh every
   * build, produced 48 new banner filenames per Publish for artwork that had
   * not changed. A local file hashes from its CONTENT, so the name moves only
   * when the artwork does and a returning visitor keeps what it cached.
   */
  src: ImageMetadata;
  /**
   * Shown in the admin only. The slides themselves are decorative and carry
   * `alt=""` — they are marketing posters whose content is baked-in text that
   * alt cannot reproduce, and every product on them is a real item in the
   * catalogue below. See the note at the top of `Hero.astro`.
   */
  name: string;
  order: number;
}

/*
 * Every banner file on disk, eagerly, so the metadata Astro needs is available
 * without an extra await per slide. The directory is generated by
 * tools/fetch-banners.mjs and holds exactly the enabled banners — it is
 * emptied first — so eager costs nothing that is not about to be rendered.
 *
 * Root-absolute glob gives root-absolute keys, which is what the lookup below
 * builds. A relative pattern would key on a path relative to THIS file and the
 * lookup would silently miss every time.
 */
const bannerFiles = import.meta.glob<{ default: ImageMetadata }>(
  '/src/assets/banners/*.{jpg,jpeg,png}',
  { eager: true },
);

/**
 * The banners the hero should show, in the order it should show them.
 *
 * Filtering and sorting happen HERE rather than in the component, so a future
 * Postgres-backed implementation can push both into the query without any
 * caller changing. Same principle as `catalog.ts` computing product counts and
 * related products inside the module.
 *
 * **The carousel's clock is derived from the length of what this returns** —
 * the keyframe stops, the pip count and the cycle length are one system. See
 * `Hero.astro`, which computes all three rather than hard-coding them.
 */
export async function getHeroBanners(): Promise<HeroBanner[]> {
  /*
   * UNCONFIGURED RETURNS AN EMPTY LIST, and the hero renders its designed empty
   * band. There is no offline banner path: the artwork lives in storage, and
   * inventing a second source would mean two rendering routes in Hero.astro for
   * a state nobody is in. A build with no database still produces a home page.
   */
  if (!configured('SUPABASE_URL', 'SUPABASE_SERVICE_ROLE_KEY')) return [];

  const { createClient } = await import('@supabase/supabase-js');
  const supabase = createClient(env('SUPABASE_URL'), env('SUPABASE_SERVICE_ROLE_KEY'), {
    auth: { persistSession: false, autoRefreshToken: false },
  });

  const { data, error } = await supabase
    .from('hero_banners')
    .select('id, path, name, order')
    .eq('enabled', true)
    .order('order', { ascending: true })
    .order('created_at', { ascending: true });
  if (error) throw new Error(`hero banners could not be read: ${error.message}`);

  const rows = (data ?? []) as Array<Omit<HeroBanner, 'src'> & { path: string }>;

  return rows.map(({ path, ...banner }) => {
    const loader = bannerFiles[`/src/assets/banners/${path}`];

    /*
     * Loud, for the reason Hero.astro has always given: a banner that cannot be
     * resolved must fail the build rather than render a gap. The home page is
     * the one page where a silent hole is least acceptable.
     *
     * Reaching here means the row says enabled and the file is not on disk,
     * which in practice means `tools/fetch-banners.mjs` did not run — the
     * `build` script chains it ahead of `astro build` precisely so that cannot
     * happen quietly.
     */
    if (!loader) {
      throw new Error(
        `hero banner "${path}" is enabled but is not in src/assets/banners/. ` +
          'Run `node tools/fetch-banners.mjs run`, which `npm run build` does for you.',
      );
    }

    return { ...banner, src: loader.default };
  });
}

/** How long each slide sits still, and how long it takes to move. */
const HOLD_SECONDS = 6;
const SLIDE_SECONDS = 1;

export interface HeroClock {
  /** Total cycle length. Every animation in the carousel runs at this. */
  cycleSeconds: number;
  /** One slide's share of the cycle, as a percentage. */
  stepPct: number;
  /** How far into its own step a slide is still holding, as a percentage. */
  holdPct: number;
  /** `animation-delay` for each pip, in seconds, one per slide. */
  pipDelays: number[];
}

/**
 * The carousel's clock, derived from the slide count.
 *
 * THE KEYFRAME STOPS, THE PIP STAGGER AND THE CYCLE LENGTH ARE ONE SYSTEM.
 * They were three sets of literals in `Hero.astro` until 2026-08-19, all
 * assuming exactly six slides — so enabling a seventh banner would have
 * produced a carousel whose lit pip reported a slide that was not showing.
 * That reads as a rendering bug and is arithmetic, which is the worst kind to
 * find.
 *
 * Pure and exported so the arithmetic is testable without a browser. At six
 * slides it returns exactly the values that used to be hard-coded: a 42s cycle,
 * stops at 16.667% and 14.286%, and pips every 7s.
 */
export function heroClock(slideCount: number): HeroClock {
  if (slideCount < 1) throw new Error(`heroClock needs at least one slide, got ${slideCount}`);

  const perSlide = HOLD_SECONDS + SLIDE_SECONDS;
  const stepPct = 100 / slideCount;

  return {
    cycleSeconds: slideCount * perSlide,
    stepPct,
    holdPct: stepPct * (HOLD_SECONDS / perSlide),
    pipDelays: Array.from({ length: slideCount }, (_, i) => i * perSlide),
  };
}

/**
 * True when `site.phone` is still a placeholder rather than a number a buyer
 * can dial.
 *
 * WHY THIS IS A HEURISTIC AND NOT A FLAG IN site.json. A flag has to be flipped
 * by the same person who types the real number, and the failure mode of
 * forgetting is a `tel:` link that dials nothing on every page — which is the
 * exact defect this exists to prevent. A heuristic heals itself.
 *
 * WHY THE THRESHOLD IS FOUR ZEROS AND NOT THREE. The client's real WhatsApp
 * number is `+973 3800 0458`, whose digits contain `000`. At three this would
 * classify a working number as a placeholder and hide it. Four is the smallest
 * run that clears every real number on file and still catches
 * `+971 00 000 0000`, which carries nine. `site-content.phone.test.ts` pins
 * both directions, and the WhatsApp case is the one that would break silently.
 *
 * The length floor catches the empty string and any half-typed fragment. Seven
 * is the shortest national subscriber number in use anywhere; below that there
 * is nothing to dial.
 */
export function isPlaceholderNumber(phone: string): boolean {
  const digits = phone.replace(/\D/g, '');
  return digits.length < 7 || /0{4,}/.test(digits);
}
