/**
 * The canonical counts, generated from the repository.
 *
 *   node tools/counts.mjs          print the block
 *   node tools/counts.mjs --write  write it into CLAUDE.md and AGENTS.md
 *
 * WHY THIS EXISTS
 *
 * On 2026-08-10 the docs stated 63 unit tests in five places — handoff.md three
 * times, README.md twice — against an actual 104. improve.md argued "146 tests
 * exist because each one was worth writing", an argument resting on a dead
 * number. handoff.md:249 already carried the warning "72 is correct — if you
 * see 74 anywhere, it is stale", which is the project defending against this
 * exact failure with prose and losing.
 *
 * So there is now one live copy of every volatile number, it is generated, and
 * `npm run verify` fails when it drifts. Everywhere else either points here or
 * is explicitly dated history.
 *
 * WHY THIS MIRRORS tools/csp.mjs
 *
 * Same problem, same shape: a value that must track the build, whose staleness
 * nothing else notices. The CSP tool is already trusted and already in the
 * loop's muscle memory, so this one is deliberately not novel.
 *
 * WHY THE E2E COUNT IS NOT HERE
 *
 * Writing it would mean a full Playwright run on every regeneration — minutes,
 * every time. A tool expensive enough to avoid is a tool that gets avoided, and
 * an omitted number costs less than an unused gate.
 */
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

export const MARKERS = {
  start: '<!-- counts:start — generated by `npm run counts`; `npm run verify` fails when stale -->',
  end: '<!-- counts:end -->',
};

/** Both twins carry the block, because gate 12 compares them byte for byte. */
export const TARGETS = ['CLAUDE.md', 'AGENTS.md'];

const json = (rel) => JSON.parse(fs.readFileSync(path.join(root, rel), 'utf8'));

/** Every built HTML page, including 404.html. */
function builtPages(dir) {
  if (!fs.existsSync(dir)) return 0;
  let total = 0;
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) total += builtPages(full);
    else if (entry.name.endsWith('.html')) total += 1;
  }
  return total;
}

/**
 * Routes that opt out of prerendering.
 *
 * handoff.md called `/api/enquiry` "the only server-rendered route" and said
 * nothing else may set the flag "without a reason as good". The admin dashboard
 * was that reason and the decision is recorded in its design doc — but the
 * count went stale anyway, in three documents. Counting the flag is cheaper
 * than remembering to.
 */
function ssrRoutes(dir = path.join(root, 'src/pages')) {
  let total = 0;
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) total += ssrRoutes(full);
    else if (/\.(astro|ts)$/.test(entry.name)) {
      const text = fs.readFileSync(full, 'utf8');
      if (/export\s+const\s+prerender\s*=\s*false/.test(text)) total += 1;
    }
  }
  return total;
}

/** Only used by `--write`. verify.mjs has already run vitest and passes its number in. */
function runVitest() {
  try {
    const out = execFileSync('npx', ['vitest', 'run'], {
      cwd: root,
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'pipe'],
      shell: process.platform === 'win32',
      maxBuffer: 64 * 1024 * 1024,
    });
    return Number(out.match(/Tests\s+(\d+) passed/)?.[1] ?? 0);
  } catch {
    return 0;
  }
}

/**
 * @typedef {object} Counts
 * @property {number} products
 * @property {number} categories
 * @property {number} divisions
 * @property {number} ssrRoutes
 * @property {number} builtPages
 * @property {number} cspHashes
 * @property {number} unitTests
 */

/**
 * JSDoc is load-bearing here, not decoration. `tsconfig.json` includes `**\/*`
 * with `allowJs`, so `astro check` — gate 1 — typechecks the .test.ts that
 * imports this and infers this signature from the source. Without the
 * annotation TS reads `{ unitTests } = {}` as `{ unitTests?: undefined }` and
 * rejects `computeCounts({ unitTests: 104 })` at the only call site that
 * matters.
 *
 * @param {{ unitTests?: number }} [opts]
 * @returns {Counts}
 */
export function computeCounts({ unitTests } = {}) {
  const vercel = fs.readFileSync(path.join(root, 'vercel.json'), 'utf8');
  return {
    products: json('src/data/products.json').length,
    categories: json('src/data/categories.json').length,
    divisions: json('src/data/divisions.json').length,
    ssrRoutes: ssrRoutes(),
    builtPages: builtPages(path.join(root, 'dist/client')),
    cspHashes: (vercel.match(/sha256-/g) ?? []).length,
    unitTests: unitTests ?? runVitest(),
  };
}

/**
 * @param {Counts} c
 * @returns {string}
 */
export function renderBlock(c) {
  return [
    MARKERS.start,
    '',
    `**${c.products} products** across **${c.categories} categories**, in **${c.divisions} divisions**.`,
    '',
    `**${c.builtPages} built pages** · **${c.ssrRoutes} server-rendered routes** · ` +
      `**${c.cspHashes} inline-script CSP hashes** · **${c.unitTests} unit tests**.`,
    '',
    MARKERS.end,
  ].join('\n');
}

/*
 * Deliberately returns null rather than appending when the markers are absent.
 * Appending would produce a second block on the next run and the gate would
 * then compare against whichever one the regex reached first — a gate that
 * passes while the visible number is wrong.
 */
const BLOCK = /<!-- counts:start[\s\S]*?<!-- counts:end -->/;

/**
 * @param {string} text
 * @param {string} block
 * @returns {string | null} null when `text` carries no markers
 */
export function replaceBlock(text, block) {
  if (!BLOCK.test(text)) return null;
  return text.replace(BLOCK, block);
}

/* ------------------------------------------------------------------ main -- */

if (process.argv[1]?.endsWith('counts.mjs')) {
  if (!fs.existsSync(path.join(root, 'dist/client'))) {
    console.error('dist/client does not exist. Run `npm run build` first.');
    process.exit(1);
  }

  const counts = computeCounts();
  const block = renderBlock(counts);

  if (!process.argv.includes('--write')) {
    console.log(block);
    process.exit(0);
  }

  for (const rel of TARGETS) {
    const file = path.join(root, rel);
    const text = fs.readFileSync(file, 'utf8');
    const next = replaceBlock(text, block);
    if (next === null) {
      console.error(
        `${rel} has no counts block. Add these two lines where it belongs and re-run:\n\n${MARKERS.start}\n${MARKERS.end}\n`,
      );
      process.exit(1);
    }
    fs.writeFileSync(file, next);
  }

  console.log(`${TARGETS.join(' and ')} updated — ${counts.unitTests} unit tests, ${counts.builtPages} pages.`);
}
