/**
 * Brings up a throwaway Supabase stack for the authenticated admin tests.
 *
 * WHY THIS EXISTS. Proving the edit screens work means actually saving a
 * product, and there is only one real database: the live one. A test that
 * proved editing worked would be editing the client's catalogue, and a test
 * that reached Publish would deploy the production site. So the tests get their
 * own database, created and destroyed around them.
 *
 * The test admin is created here rather than seeded from SQL because Supabase
 * Auth owns its own user table and hashing. Creating it through the admin API
 * is the only way to get a user that can actually sign in.
 *
 * The catalogue is seeded here too, and NOT left to `supabase/config.toml`'s
 * `[db.seed] sql_paths = ["./seed.sql"]`. That path is relative to the
 * `supabase/` directory, so it resolves to `supabase/seed.sql` — but the
 * generated file lives at the repo root (`seed.sql` is gitignored precisely
 * because it is a derived copy of `src/data/*.json`, regenerated by
 * `tools/seed-catalogue.mjs`, never committed). `supabase start` looks for it
 * in the wrong place, prints `WARN: no files matched pattern:
 * supabase/seed.sql`, and leaves every catalogue table empty — confirmed by
 * running it cold. So this script generates the seed SQL in-process from
 * `tools/seed-catalogue.mjs` and feeds it to `psql` inside the db container
 * directly, which is also idempotent: every statement is `on conflict do
 * update`, so reseeding an already-seeded stack is a no-op rewrite, not a
 * duplicate.
 *
 * The missing GRANTs that made this script fail on a cold start are fixed in
 * the schema now, not here. A rebuilt database had tables `service_role` could
 * not write to, because Supabase issues those grants itself for anything made
 * through Studio and a hand-written `create table` never gets them.
 *
 * That belongs in a migration rather than in test tooling: these migrations are
 * the disaster-recovery artifact for this database, and one that rebuilds
 * tables the application cannot write to is not a recovery path. See
 * supabase/migrations/20260820120000_table_grants.sql, which also explains why
 * granting `anon` everything is harmless while RLS carries zero policies.
 */
import { execFileSync } from 'node:child_process';
import { existsSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';
import { createClient } from '@supabase/supabase-js';
import { seedSql } from './seed-catalogue.mjs';

/**
 * Where Docker's CLI lives, resolved rather than assumed.
 *
 * This was a hard-coded path to one developer's machine until 2026-08-20, which
 * worked exactly until the repository was opened on a second computer. Docker
 * Desktop on Windows installs per-user under AppData when it is installed
 * without administrator rights and into Program Files when it is not, so there
 * is no single correct answer to hard-code.
 *
 * The Supabase CLI shells out to `docker`, so it needs the directory on PATH
 * even when this script itself never calls it directly.
 */
const DOCKER_CANDIDATES = [
  join(homedir(), 'AppData', 'Local', 'Programs', 'DockerDesktop', 'resources', 'bin'),
  join('C:', 'Program Files', 'Docker', 'Docker', 'resources', 'bin'),
  '/usr/local/bin',
  '/usr/bin',
];

/** Empty when `docker` is already on PATH, which is the case on Linux and CI. */
function dockerBin() {
  try {
    execFileSync('docker', ['--version'], { stdio: 'ignore', shell: true });
    return '';
  } catch {
    // Not on PATH. Fall through and look in the usual places.
  }

  const found = DOCKER_CANDIDATES.find((dir) => existsSync(join(dir, 'docker.exe')) || existsSync(join(dir, 'docker')));
  if (found) return found;

  throw new Error(
    'Docker could not be found. It is required for the throwaway test database.\n' +
      'Install Docker Desktop and start it, or add its bin directory to PATH.\n' +
      `Looked in: ${DOCKER_CANDIDATES.join(', ')}`,
  );
}

const DOCKER_BIN = dockerBin();

/** Fixed by `project_id = "spartan"` in supabase/config.toml. */
const DB_CONTAINER = 'supabase_db_spartan';

export const TEST_ADMIN = { email: 'test-admin@spartan.local', password: 'test-admin-password-1' };

const cliEnv = () => ({
  ...process.env,
  PATH: DOCKER_BIN ? `${process.env.PATH};${DOCKER_BIN}` : process.env.PATH,
});

const run = (args) =>
  execFileSync('npx', ['--yes', 'supabase@latest', ...args], {
    stdio: 'inherit',
    shell: true,
    env: cliEnv(),
  });

const capture = (args) =>
  execFileSync('npx', ['--yes', 'supabase@latest', ...args], {
    encoding: 'utf8',
    shell: true,
    env: cliEnv(),
  });

/** Runs SQL against the db container as the `postgres` superuser. */
function psql(sql) {
  execFileSync(
    'docker',
    ['exec', '-i', DB_CONTAINER, 'psql', '-U', 'postgres', '-d', 'postgres', '-v', 'ON_ERROR_STOP=1'],
    { input: sql, encoding: 'utf8', shell: true, env: cliEnv() },
  );
}

/** Feeds the generated catalogue seed straight to psql inside the db container. */
function seedCatalogue() {
  psql(seedSql().join('\n') + '\n');
}

export async function start() {
  run(['start']);

  seedCatalogue();

  const status = JSON.parse(capture(['status', '-o', 'json']));
  const url = status.API_URL;
  const serviceKey = status.SERVICE_ROLE_KEY;

  const db = createClient(url, serviceKey, { auth: { persistSession: false } });

  // Idempotent: `supabase start` on an existing container keeps its data.
  const { data: existing } = await db.auth.admin.listUsers();
  let user = existing?.users.find((u) => u.email === TEST_ADMIN.email);
  if (!user) {
    const { data, error } = await db.auth.admin.createUser({
      email: TEST_ADMIN.email,
      password: TEST_ADMIN.password,
      email_confirm: true,
    });
    if (error) throw new Error(`could not create the test admin: ${error.message}`);
    user = data.user;
  }

  /*
   * Membership of `admins` is the whole permission model. A Supabase Auth user
   * that is not in this table cannot reach a single admin page.
   *
   * KEYED ON user_id, NOT email. `public.admins` is
   * `user_id uuid primary key references auth.users(id)`, and `email` carries
   * no unique constraint, so an upsert with `onConflict: 'email'` fails. The
   * auth user has to exist first because the foreign key demands it, which is
   * why this runs after createUser rather than beside it.
   */
  const { error: allowError } = await db
    .from('admins')
    .upsert({ user_id: user.id, email: TEST_ADMIN.email }, { onConflict: 'user_id' });
  if (allowError) throw new Error(`could not allow-list the test admin: ${allowError.message}`);

  return { url, serviceKey };
}

export function stop() {
  run(['stop', '--no-backup']);
}

if (process.argv[2] === 'start') await start();
if (process.argv[2] === 'stop') stop();
